# Generated by Django 3.2.9 on 2021-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stonk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('name', models.CharField(max_length=100, verbose_name='Stock Name')),
                ('numShares', models.IntegerField(default=20, verbose_name='Shares')),
                ('purchaseDate', models.DateField(auto_now_add=True, verbose_name='Purchase Date')),
            ],
        ),
    ]
