# Generated by Django 3.2.9 on 2021-11-24 12:52

from django.db import migrations

def create_data(apps, schema_editor):
    StonkA = apps.get_model('stonks_app', 'Stonk')
    StonkA(ticker="GME", name="GameStop Corp.", numShares="100").save()
    StonkB = apps.get_model('stonks_app', 'Stonk')
    StonkB(ticker="TSLA", name="Tesla Inc.", numShares="100").save()
    StonkC = apps.get_model('stonks_app', 'Stonk')
    StonkC(ticker="NVDA", name="NVIDIA Corporation", numShares="100").save()

class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
